// // Mocks generated by Mockito 5.0.9 from annotations
// // in flutter_start_repo/test/unit_test/mock_test.dart.
// // Do not manually edit this file.
//
// import 'dart:async' as _i4;
//
// import 'package:flutter_start_repo/features/login/data/models/User.dart' as _i2;
// import 'package:flutter_start_repo/features/login/data/repositories/UserRepositoryImpl.dart' as _i3;
// import 'package:mockito/mockito.dart' as _i1;
//
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: comment_references
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
//
// class _FakeUser extends _i1.Fake implements _i2.User {}
//
// /// A class which mocks [UserRepository].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockUserRepository extends _i1.Mock implements _i3.UserRepositoryImpl {
//   MockUserRepository() {
//     _i1.throwOnMissingStub(this);
//   }
//
//   @override
//   _i4.Future<_i2.User> authenticateUser(dynamic username, dynamic password) =>
//       (super.noSuchMethod(
//               Invocation.method(#authenticateUser, [username, password]),
//               returnValue: Future<_i2.User>.value(_FakeUser()))
//           as _i4.Future<_i2.User>);
//   @override
//   _i4.Future<Map<dynamic, dynamic>> registerUser(
//           Map<String, dynamic>? register) =>
//       (super.noSuchMethod(Invocation.method(#registerUser, [register]),
//               returnValue:
//                   Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
//           as _i4.Future<Map<dynamic, dynamic>>);
//   @override
//   _i4.Future<bool> deleteUserInfo() =>
//       (super.noSuchMethod(Invocation.method(#deleteUserInfo, []),
//           returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
//   @override
//   _i4.Future<bool> persistUserInfo(_i2.User? user) =>
//       (super.noSuchMethod(Invocation.method(#persistUserInfo, [user]),
//           returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
// }
//
// /// A class which mocks [UserRepository].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class UserRepositoryMock extends _i1.Mock implements _i3.UserRepositoryImpl {
//   @override
//   _i4.Future<_i2.User> authenticateUser(dynamic username, dynamic password) =>
//       (super.noSuchMethod(
//               Invocation.method(#authenticateUser, [username, password]),
//               returnValue: Future<_i2.User>.value(_FakeUser()))
//           as _i4.Future<_i2.User>);
//   @override
//   _i4.Future<Map<dynamic, dynamic>> registerUser(
//           Map<String, dynamic>? register) =>
//       (super.noSuchMethod(Invocation.method(#registerUser, [register]),
//               returnValue:
//                   Future<Map<dynamic, dynamic>>.value(<dynamic, dynamic>{}))
//           as _i4.Future<Map<dynamic, dynamic>>);
//   @override
//   _i4.Future<bool> deleteUserInfo() =>
//       (super.noSuchMethod(Invocation.method(#deleteUserInfo, []),
//           returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
//   @override
//   _i4.Future<bool> persistUserInfo(_i2.User? user) =>
//       (super.noSuchMethod(Invocation.method(#persistUserInfo, [user]),
//           returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
// }
