version: 2
jobs:
  build:
    branches:
        only:
        - develop
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk
      - store_artifacts:
          path: build/app/outputs/apk/
          destination: apks/